# Generated by Django 6.1.1 on 2026-09-17 15:56

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_displaycard_displaylink_delete_displaycards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaylink',
            name='card',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='home.displaycard'),
        ),
    ]
