# Generated by Django 6.1.1 on 2026-09-17 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_displaylink_card'),
        migrations.swappable_dependency(settings.WAGTAIL_PAGE_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='displaycard',
            name='card_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='displaylink',
            name='linked_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.WAGTAIL_PAGE_MODEL),
        ),
    ]
