# Generated by Django 6.1.1 on 2026-09-17 16:36

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_displaycard_card_name_displaylink_linked_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaylink',
            name='card',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='home.displaycard'),
        ),
    ]
